---

- name: Install apache and php
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Mariadb service
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Mariadb Restarting/Enabling
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: Install Nagios Monitoring Tool
  apt:
    name:
      - nagios4
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
